---
name: Deploy local TG
on: 
  push:
    branches: [main]
  workflow_dispatch:
concurrency: "${{ github.workflow }}-${{ github.ref }}"
########################################################################################
jobs:
  start_local:
    name: Start Test George
    runs-on: self-hosted
    environment: ${{ inputs.environmentName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ inputs.prRef }}
