---
name: Deploy local TG
on: 
  push:
    branches: [main]
  workflow_dispatch:
concurrency: "${{ github.workflow }}-${{ github.ref }}"
########################################################################################
jobs:
  run-deploy-tre-main:
    name: "Deploy main TG"
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy_tre_reusable.yml
    with:
      ciGitRef: ${{ github.ref }}
      environmentName: CICD
